name: Build Tailscale for Windows

on:
  workflow_dispatch:  # 手动触发
  push:
    branches: [ main ]  # 或你自己的分支名

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'  # Tailscale 推荐版本

    - name: Install Dependencies
      run: go mod download

    - name: Build tailscaled.exe
      run: |
        GOOS=windows GOARCH=amd64 go build -o tailscaled.exe ./cmd/tailscaled

    - name: Build tailscale.exe
      run: |
        GOOS=windows GOARCH=amd64 go build -o tailscale.exe ./cmd/tailscale

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tailscale-windows
        path: |
          tailscaled.exe
          tailscale.exe
